//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPeeker.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTPK_Logs
    {
        public int ID { get; set; }
        public string Action { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public string UserID { get; set; }
        public System.DateTime LogDate { get; set; }
        public int SiteID { get; set; }
    
        public virtual FTPK_FTPs FTPK_FTPs { get; set; }
    }
}
