
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FTPeeker.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class FTPK_Auth_Types
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FTPK_Auth_Types()
    {

        this.FTPK_FTPs = new HashSet<FTPK_FTPs>();

    }


    public string TypeCode { get; set; }

    public string TypeDesc { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FTPK_FTPs> FTPK_FTPs { get; set; }

}

}
