
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FTPeeker.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class FTPK_FTPs
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FTPK_FTPs()
    {

        this.FTPK_Logs = new HashSet<FTPK_Logs>();

    }


    public int ID { get; set; }

    public string DisplayName { get; set; }

    public string Host { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public int Port { get; set; }

    public string AuthTypeCode { get; set; }

    public string SSHKeyPath { get; set; }

    public string SSHKeyPassword { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FTPK_Logs> FTPK_Logs { get; set; }

    public virtual FTPK_Auth_Types FTPK_Auth_Types { get; set; }

}

}
