
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FTPeeker.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class FTPK_Permissions
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FTPK_Permissions()
    {

        this.FTPK_User_Permissions = new HashSet<FTPK_User_Permissions>();

    }


    public string PermissionCode { get; set; }

    public string PermissionDesc { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FTPK_User_Permissions> FTPK_User_Permissions { get; set; }

}

}
