USE [YOUR_DATABASE_NAME]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FTPK_FTPs](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DisplayName] [varchar](100) NOT NULL,
	[Host] [varchar](100) NOT NULL,
	[UserName] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
	[Port] [int] NOT NULL,
 CONSTRAINT [PK_FTPK_FTPs] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FTPK_Logs](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Action] [varchar](50) NOT NULL,
	[FileName] [varchar](500) NOT NULL,
	[Path] [varchar](500) NOT NULL,
	[UserID] [varchar](500) NOT NULL,
	[LogDate] [datetime] NOT NULL,
	[SiteID] [int] NOT NULL,
 CONSTRAINT [PK_FTPK_Logs] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FTPK_Logs]  WITH CHECK ADD  CONSTRAINT [FK_FTPK_Logs_FTPK_FTPs] FOREIGN KEY([SiteID])
REFERENCES [dbo].[FTPK_FTPs] ([ID])
GO

ALTER TABLE [dbo].[FTPK_Logs] CHECK CONSTRAINT [FK_FTPK_Logs_FTPK_FTPs]
GO
